export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  category: "trends" | "vision" | "kitchen";
  categoryLabel: string;
  author: string;
  readTime: string;
  pinned?: boolean;
  imageUrl?: string;
}

export const CATEGORIES = [
  { id: "all", label: "All" },
  { id: "trends", label: "Trends & Agenda" },
  { id: "vision", label: "Vision & Philosophy" },
  { id: "kitchen", label: "Kitchen (Know-How)" },
] as const;

const FULL_POSTS_LIST = [
  {
    slug: "calm-tech-101",
    title: "Calm Tech 101: Why Tech Should Leave You Alone, Instead of Constantly Sending You Notifications",
    excerpt: "Technology Shouldn’t Steal Your Attention; It Should Provide You with Calm and Productivity. Learn about the eight core principles of Calm Technology.",
    date: "October 2, 2025",
    category: "vision",
    categoryLabel: "Vision & Philosophy",
    author: "Appibara Team",
    readTime: "4 min read",
    pinned: true,
    imageUrl: "/blog/calm-tech-101/cover.png",
  },
  {
    slug: "why-calm-tech-will-define-the-experience-of-the-future",
    title: "Why Calm Tech Will Define the Experience of the Future",
    excerpt: "The future of experience isn't shaped by blaring technologies, but by technologies that work silently with us. Explore the economy of serenity and emotional layers of design.",
    date: "October 9, 2025",
    category: "vision",
    categoryLabel: "Vision & Philosophy",
    author: "Appibara Team",
    readTime: "4 min read",
    imageUrl: "/blog/why-calm-tech-will-define-the-experience-of-the-future/cover.png",
  },
  {
    slug: "is-ux-still-human-centered",
    title: "Is UX Still Human-Centered?",
    excerpt: "Is the world of design serving people, or is it now focused on the goals of products? A look at the history and strategic evolution of user experience design.",
    date: "October 16, 2025",
    category: "vision",
    categoryLabel: "Vision & Philosophy",
    author: "Appibara Team",
    readTime: "3 min read",
    imageUrl: "/blog/is-ux-still-human-centered/cover.png",
  },
  {
    slug: "why-emotional-design-still-matters",
    title: "Why Emotional Design Still Matters?",
    excerpt: "In an era where AI can write, draw, and even ‘feel’, emotional design isn’t just an aesthetic choice; it’s how products stay human.",
    date: "October 23, 2025",
    category: "vision",
    categoryLabel: "Vision & Philosophy",
    author: "Appibara Team",
    readTime: "4 min read",
    imageUrl: "/blog/why-emotional-design-still-matters/cover.png",
  },
  {
    slug: "what-is-an-mvp",
    title: "What Is an MVP? How to Know If Your Product Is Truly Viable",
    excerpt: "When transforming an idea into a product, understanding whether it is truly ‘viable’ is actually the most critical test.",
    date: "October 30, 2025",
    category: "kitchen",
    categoryLabel: "Kitchen (Know-How)",
    author: "Appibara Team",
    readTime: "4 min read",
    imageUrl: "/blog/what-is-an-mvp/cover.png",
  },
  {
    slug: "stop-guessing-start-measuring",
    title: "Stop Guessing, Start Measuring",
    excerpt: "Connecting UX design decisions to business return on investment (ROI) is no longer a luxury; it is a vital strategy to build products that survive.",
    date: "November 6, 2025",
    category: "kitchen",
    categoryLabel: "Kitchen (Know-How)",
    author: "Appibara Team",
    readTime: "5 min read",
    imageUrl: "/blog/stop-guessing-start-measuring/cover.jpeg",
  },
  {
    slug: "what-happens-when-you-let-people-think-without-limits",
    title: "What Happens When You Let People Think Without Limits?",
    excerpt: "How Blue Sky Thinking Drives Innovation, Creativity, and Strategic Growth",
    date: "November 13, 2025",
    category: "vision",
    categoryLabel: "Vision & Philosophy",
    author: "Appibara Team",
    readTime: "5 min read",
    imageUrl: "/blog/what-happens-when-you-let-people-think-without-limits/cover.png",
  },
  {
    slug: "the-ceo-of-the-numbers-and-the-people-in-the-profit-loss-ledger",
    title: "The CEO of the Numbers and the People in the Profit-Loss Ledger",
    excerpt: "Values ​​lost in the shadow of financial logic and the intrigue of the CEO.",
    date: "November 20, 2025",
    category: "vision",
    categoryLabel: "Vision & Philosophy",
    author: "Appibara Team",
    readTime: "5 min read",
    imageUrl: "/blog/the-ceo-of-the-numbers-and-the-people-in-the-profit-loss-ledger/cover.png",
  },
  {
    slug: "why-a-slack-message-steals-25-minutes-of-a-developers-time",
    title: "Why a Slack Message Steals 25 Minutes of a Developer’s Time",
    excerpt: "How Tech Noise Kills Productivity",
    date: "November 27, 2025",
    category: "kitchen",
    categoryLabel: "Kitchen (Know-How)",
    author: "Appibara Team",
    readTime: "3 min read",
    imageUrl: "/blog/why-a-slack-message-steals-25-minutes-of-a-developers-time/cover.png",
  },
  {
    slug: "why-marketing-data-misleads-ux",
    title: "Why Marketing Data Misleads UX?",
    excerpt: "Why numbers alone can’t explain user behavior — and how UX research fills the gap.",
    date: "December 4, 2025",
    category: "kitchen",
    categoryLabel: "Kitchen (Know-How)",
    author: "Appibara Team",
    readTime: "3 min read",
    imageUrl: "/blog/why-marketing-data-misleads-ux/cover.png",
  },
  {
    slug: "poc-in-ai-project-what-to-prove-and-what-not-to-prove",
    title: "PoC in AI Project: What to Prove and What Not to Prove?",
    excerpt: "A practical guide to validating AI ideas, avoiding common PoC pitfalls, and building a realistic path from concept to production.",
    date: "December 11, 2025",
    category: "kitchen",
    categoryLabel: "Kitchen (Know-How)",
    author: "Appibara Team",
    readTime: "5 min read",
    imageUrl: "/blog/poc-in-ai-project-what-to-prove-and-what-not-to-prove/cover.png",
  },
  {
    slug: "do-we-have-to-deal-with-the-backend-when-building-an-mvp",
    title: "Do we have to deal with the backend when building an MVP?",
    excerpt: "How Backendless and Serverless Approaches Speed Up MVP Development",
    date: "December 18, 2025",
    category: "kitchen",
    categoryLabel: "Kitchen (Know-How)",
    author: "Appibara Team",
    readTime: "3 min read",
    imageUrl: "/blog/do-we-have-to-deal-with-the-backend-when-building-an-mvp/cover.png",
  },
  {
    slug: "designing-trust-not-screens",
    title: "Designing Trust, Not Screens",
    excerpt: "The 6C Framework for Building Trust in Modern UX",
    date: "December 25, 2025",
    category: "vision",
    categoryLabel: "Vision & Philosophy",
    author: "Appibara Team",
    readTime: "4 min read",
    imageUrl: "/blog/designing-trust-not-screens/cover.png",
  },
  {
    slug: "prompt-and-pray-are-you-gambling-with-generative-ai",
    title: "Prompt and Pray: Are you Gambling with Generative AI?",
    excerpt: "The Failure of Strategic Thinking and the Paradox of Uncertainity in AI Interaction",
    date: "March 24, 2026",
    category: "trends",
    categoryLabel: "Trends & Agenda",
    author: "Appibara Team",
    readTime: "3 min read",
    imageUrl: "/blog/prompt-and-pray-are-you-gambling-with-generative-ai/cover.png",
  },
  {
    slug: "architecture-as-a-product-why-your-tech-stack-is-your-biggest-ux-constraint",
    title: "Architecture as a Product: Why Your Tech Stack is Your Biggest UX Constraint",
    excerpt: "Stop treating your backend as a black box and start seeing it as the foundation of your user’s emotional journey.",
    date: "April 2, 2026",
    category: "kitchen",
    categoryLabel: "Kitchen (Know-How)",
    author: "Appibara Team",
    readTime: "3 min read",
    imageUrl: "/blog/architecture-as-a-product-why-your-tech-stack-is-your-biggest-ux-constraint/cover.png",
  },
  {
    slug: "the-time-to-value-trap-why-your-onboarding-is-killing-your-saas-and-how-to-fix-it",
    title: "The “Time-to-Value” Trap: Why Your Onboarding is Killing Your SaaS (And How to Fix It)",
    excerpt: "Why “interrogation” forms and the Cold Start Problem are destroying your conversion rates — and how progressive profiling can save them.",
    date: "April 9, 2026",
    category: "kitchen",
    categoryLabel: "Kitchen (Know-How)",
    author: "Appibara Team",
    readTime: "3 min read",
    imageUrl: "/blog/the-time-to-value-trap-why-your-onboarding-is-killing-your-saas-and-how-to-fix-it/cover.png",
  },
  {
    slug: "you-cant-craft-while-sprinting-the-lost-takumi-spirit-in-software-engineering",
    title: "You Can’t Craft While Sprinting: The Lost “Takumi” Spirit in Software Engineering",
    excerpt: "Our obsession with 2-week sprints turned teams into feature factories. It’s time to bring craftsmanship back to code.",
    date: "April 14, 2026",
    category: "vision",
    categoryLabel: "Vision & Philosophy",
    author: "Appibara Team",
    readTime: "2 min read",
    imageUrl: "/blog/you-cant-craft-while-sprinting-the-lost-takumi-spirit-in-software-engineering/cover.png",
  },
  {
    slug: "from-1960s-counterculture-to-the-ai-era-the-evolution-of-vibe-design",
    title: "From 1960s Counterculture to the AI Era: The Evolution of “Vibe Design”",
    excerpt: "From the 1960s counterculture to modern AI tools, discover why humans must stop pushing pixels and start crafting souls.",
    date: "April 21, 2026",
    category: "vision",
    categoryLabel: "Vision & Philosophy",
    author: "Appibara Team",
    readTime: "5 min read",
    imageUrl: "/blog/from-1960s-counterculture-to-the-ai-era-the-evolution-of-vibe-design/cover.jpg",
  },
  {
    slug: "the-betty-crocker-paradox-why-using-ai-feels-like-cheating-and-how-to-fix-it",
    title: "The Betty Crocker Paradox: Why Using AI Feels Like Cheating (And How to Fix It)",
    excerpt: "For years, UX obsessed over removing all friction. But in the AI era, adding “meaningful friction” is the secret to building products users",
    date: "April 30, 2026",
    category: "vision",
    categoryLabel: "Vision & Philosophy",
    author: "Appibara Team",
    readTime: "4 min read",
    imageUrl: "/blog/the-betty-crocker-paradox-why-using-ai-feels-like-cheating-and-how-to-fix-it/cover.png",
  },
  {
    slug: "ai-wrote-the-code-why-am-i-to-blame-the-silent-responsibility-crisis-in-software-engineering",
    title: "“AI Wrote the Code, Why Am I to Blame?”: The Silent Responsibility Crisis in Software Engineering",
    excerpt: "AI gave us speed, but destroyed accountability. How to stop “blind approvals” and rebuild a culture of trust in engineering.",
    date: "May 5, 2026",
    category: "trends",
    categoryLabel: "Trends & Agenda",
    author: "Appibara Team",
    readTime: "3 min read",
    imageUrl: "/blog/ai-wrote-the-code-why-am-i-to-blame-the-silent-responsibility-crisis-in-software-engineering/cover.png",
  },
  {
    slug: "is-your-b2b-software-the-loudest-employee-in-the-room",
    title: "Is Your B2B Software the Loudest Employee in the Room?",
    excerpt: "Unpacking the psychology of feature bloat and the hidden cost of demanding interfaces.",
    date: "May 12, 2026",
    category: "vision",
    categoryLabel: "Vision & Philosophy",
    author: "Appibara Team",
    readTime: "4 min read",
    imageUrl: "/blog/is-your-b2b-software-the-loudest-employee-in-the-room/image1.png",
  },
] as const

export const POSTS: BlogPost[] = FULL_POSTS_LIST.slice(0, 16);


export async function getPosts(): Promise<BlogPost[]> {
  return POSTS;
}

export async function getPostBySlug(slug: string): Promise<BlogPost | undefined> {
  return POSTS.find((post) => post.slug === slug);
}
